# Generated by Django 6.0.5 on 2026-05-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0020_unique_active_usb_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliesReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Отчёт по расходникам',
                'verbose_name_plural': 'Отчёт по расходникам',
                'permissions': [('access_supplies_report', 'Доступ к отчёту по расходникам'), ('manage_supplies_report', 'Управление группами отчёта'), ('download_supplies_report', 'Скачивание .eml письма')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('location_label', models.CharField(blank=True, help_text='Подставляется в {location} в теме. Например: "г. Иркутск, ул. 5й Армии, 2А".', max_length=255, verbose_name='Локация (в теме письма)')),
                ('subject_template', models.CharField(default='{date} Состояние расходных материалов МФУ и принтеров {location}', help_text='Плейсхолдеры: {date} (дд.мм.гггг), {location}.', max_length=500, verbose_name='Шаблон темы')),
                ('body_intro', models.TextField(blank=True, default='Добрый день, коллеги\nНаправляю отчет по состоянию расходных материалов МФУ и принтеров.', verbose_name='Вступление письма')),
                ('body_signature', models.TextField(blank=True, default='', verbose_name='Подпись')),
                ('to_emails', models.TextField(blank=True, help_text='Список адресов через запятую или с новой строки.', verbose_name='Получатели To')),
                ('cc_emails', models.TextField(blank=True, help_text='Список адресов через запятую или с новой строки.', verbose_name='Получатели Cc')),
                ('from_email', models.EmailField(blank=True, help_text='Если пусто — будет использован email пользователя, скачавшего письмо.', max_length=254, verbose_name='Адрес отправителя')),
                ('stale_threshold_hours', models.PositiveIntegerField(default=24, help_text='Если последний успешный опрос старше N часов, в письме появится пометка с датой.', verbose_name="Порог 'устаревших' данных (часов)")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Группа отчёта по расходникам',
                'verbose_name_plural': 'Группы отчёта по расходникам',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, help_text='Многострочно. Пример: "5 этаж\\nкаб. 157.1".', verbose_name='Расположение')),
                ('additional_info', models.TextField(blank=True, help_text='ФИО пользователя, примечание. Пример: "Сотников А.А.\\nПриёмная Колмогорова В.В.".', verbose_name='Дополнительно')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies_report.reportgroup', verbose_name='Группа')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_group_items', to='inventory.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Принтер в группе отчёта',
                'verbose_name_plural': 'Принтеры в группе отчёта',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('group', 'printer')},
            },
        ),
    ]
