# Generated by Django 6.0.5 on 2026-05-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgroup',
            name='auto_send_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Если выключено — письмо генерируется только по кнопке.', verbose_name='Автоотправка включена'),
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='auto_send_time',
            field=models.TimeField(blank=True, help_text='Локальное время (CELERY_TIMEZONE). Например 08:00.', null=True, verbose_name='Время автоотправки'),
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='auto_send_weekdays',
            field=models.CharField(default='1,2,3,4,5', help_text='Список через запятую: 1=Пн, 2=Вт, …, 7=Вс. По умолчанию — будни.', max_length=20, verbose_name='Дни недели'),
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='last_send_error',
            field=models.TextField(blank=True, default='', help_text='Заполняется автоматически при сбое автоотправки.', verbose_name='Последняя ошибка отправки'),
        ),
        migrations.AddField(
            model_name='reportgroup',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя успешная отправка'),
        ),
    ]
