# Generated by Django 5.2.1 on 2025-09-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_contracts_app', 'Can access Contracts app'), ('export_contracts', 'Can export contracts to Excel')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
