# Generated by Django 5.2.1 on 2025-09-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractsaccess'),
        ('inventory', '0007_inventoryaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdevice',
            name='service_start_month',
            field=models.DateField(blank=True, help_text='Месяц и год начала обслуживания устройства', null=True, verbose_name='Месяц принятия на обслуживание'),
        ),
        migrations.AddIndex(
            model_name='contractdevice',
            index=models.Index(fields=['service_start_month'], name='contracts_c_service_89f3e1_idx'),
        ),
    ]
