# Generated by Django 5.2.7 on 2025-10-15 03:29

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractdevice_service_start_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название картриджа')),
                ('part_number', models.CharField(blank=True, help_text='Заводской артикул', max_length=64, verbose_name='Артикул')),
                ('color', models.CharField(choices=[('black', 'Черный'), ('cyan', 'Голубой'), ('magenta', 'Пурпурный'), ('yellow', 'Желтый'), ('color', 'Цветной'), ('other', 'Другой')], default='black', max_length=16, verbose_name='Цвет')),
                ('capacity', models.CharField(blank=True, help_text='Например: 3000 стр.', max_length=64, verbose_name='Ресурс')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
                'ordering': ['name', 'part_number'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('part_number'), name='cartridge_name_part_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='DeviceModelCartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Основной/рекомендуемый картридж для этой модели', verbose_name='Основной')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_models', to='contracts.cartridge', verbose_name='Картридж')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_cartridges', to='contracts.devicemodel', verbose_name='Модель устройства')),
            ],
            options={
                'verbose_name': 'Совместимость картриджа',
                'verbose_name_plural': 'Совместимость картриджей',
                'ordering': ['-is_primary', 'cartridge__name'],
                'unique_together': {('device_model', 'cartridge')},
            },
        ),
    ]
