# Generated by Django 6.0.7 on 2026-08-07 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_devicemodel_has_network_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_contracts_app', 'Can access Contracts app'), ('export_contracts', 'Can export contracts to Excel'), ('import_contracts', 'Can bulk import contract devices')]},
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('state', models.CharField(choices=[('draft', 'Черновик'), ('applied', 'Применена')], db_index=True, default='draft', max_length=16, verbose_name='Состояние')),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='Итоги применения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Применена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_import_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('target_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_sessions', to='contracts.contractstatus', verbose_name='Статус для загружаемых устройств')),
            ],
            options={
                'verbose_name': 'Сессия импорта',
                'verbose_name_plural': 'Сессии импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('sheet_name', models.CharField(blank=True, max_length=255, verbose_name='Лист')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='Строк разобрано')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contracts.importsession')),
            ],
            options={
                'verbose_name': 'Файл импорта',
                'verbose_name_plural': 'Файлы импорта',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='Строка в файле')),
                ('raw', models.JSONField(default=dict, verbose_name='Значения из файла')),
                ('sn_lower', models.CharField(blank=True, max_length=128, verbose_name='Серийник (нормализованный)')),
                ('resolved', models.JSONField(blank=True, default=dict, verbose_name='Найденные справочники')),
                ('classification', models.CharField(choices=[('new', 'Новое устройство'), ('match', 'Обновление'), ('moved', 'Серийник за другой организацией'), ('dup_in_file', 'Дубль серийника в пачке'), ('error', 'Ошибка')], default='new', max_length=16, verbose_name='Класс')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Предупреждения')),
                ('decision', models.CharField(choices=[('pending', 'Не решено'), ('apply', 'Применить'), ('skip', 'Пропустить')], default='pending', max_length=16, verbose_name='Решение')),
                ('apply_error', models.TextField(blank=True, verbose_name='Ошибка применения')),
                ('applied_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='contracts.contractdevice')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='contracts.importfile')),
                ('matched_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contracts.contractdevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='contracts.importsession')),
            ],
            options={
                'verbose_name': 'Строка импорта',
                'verbose_name_plural': 'Строки импорта',
                'ordering': ['file_id', 'row_number'],
                'indexes': [models.Index(fields=['session', 'classification'], name='contracts_i_session_58deba_idx'), models.Index(fields=['session', 'decision'], name='contracts_i_session_bfc61d_idx'), models.Index(fields=['session', 'sn_lower'], name='contracts_i_session_484937_idx')],
            },
        ),
    ]
