# Generated by Django 6.0.7 on 2026-08-07 02:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contractsaccess_options_importsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Подрядчик')),
                ('code', models.SlugField(help_text='Латиницей, например amb или tonex', max_length=32, unique=True, verbose_name='Код')),
                ('issue_tracker', models.CharField(choices=[('okdesk', 'Okdesk'), ('none', 'Интеграция не подключена')], default='none', help_text='Через какую интеграцию подаются заявки по устройствам этого подрядчика', max_length=16, verbose_name='Приём заявок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='provider_name_ci_unique')],
            },
        ),
        migrations.AddField(
            model_name='contractdevice',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Кто обслуживает устройство по договору', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='contracts.serviceprovider', verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_sessions', to='contracts.serviceprovider', verbose_name='Подрядчик для загружаемых устройств'),
        ),
    ]
