# Generated by Django 6.0.7 on 2026-08-09 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_serviceprovider_support_email'),
        ('inventory', '0022_add_hybrid_polling_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPollCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('glpi_active', 'Есть в GLPI, опрашивается'), ('glpi_stale', 'Есть в GLPI, данные устарели'), ('not_found', 'Нет в GLPI'), ('no_ip', 'В GLPI без IP'), ('ip_conflict', 'IP занят другим принтером'), ('error', 'Ошибка проверки')], db_index=True, max_length=16, verbose_name='Статус')),
                ('glpi_printer_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID в GLPI')),
                ('glpi_name', models.CharField(blank=True, max_length=255, verbose_name='Имя в GLPI')),
                ('glpi_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP из GLPI')),
                ('glpi_counter', models.PositiveIntegerField(blank=True, null=True, verbose_name='Счётчик в GLPI')),
                ('glpi_date', models.DateTimeField(blank=True, null=True, verbose_name='Последний опрос в GLPI')),
                ('verify_ok', models.BooleanField(blank=True, null=True, verbose_name='Пробный опрос удался')),
                ('verify_message', models.TextField(blank=True, verbose_name='Результат пробного опроса')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда пробовали опросить')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='Проверен')),
                ('contract_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopoll_candidates', to='contracts.contractdevice')),
                ('created_printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopoll_candidates', to='inventory.printer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopoll_candidates', to='contracts.importsession')),
            ],
            options={
                'verbose_name': 'Кандидат на автоопрос',
                'verbose_name_plural': 'Кандидаты на автоопрос',
                'ordering': ['serial_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'serial_number'), name='uniq_autopoll_session_serial')],
            },
        ),
    ]
