# Generated by Django 6.0.7 on 2026-08-28 09:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_autopollcandidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_contracts_app', 'Can access Contracts app'), ('export_contracts', 'Can export contracts to Excel'), ('import_contracts', 'Can bulk import contract devices'), ('manage_device_acceptance', 'Can manage device acceptance (counter, PDFs, status, service month)')]},
        ),
        migrations.AddField(
            model_name='contractdevice',
            name='initial_counter',
            field=models.PositiveIntegerField(blank=True, help_text='Показание счётчика на момент принятия устройства на обслуживание', null=True, verbose_name='Счётчик при приёмке'),
        ),
        migrations.CreateModel(
            name='AcceptanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/acceptance/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл (PDF)')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_documents', to='contracts.contractdevice', verbose_name='Устройство')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ приёмки',
                'verbose_name_plural': 'Документы приёмки',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
