# Generated by Django 6.0.7 on 2026-08-18 03:44

import contracts.models
import datetime
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_to_okdesk_groups(apps, schema_editor):
    """Выдаёт новое право всем, кто уже мог подавать заявки через Okdesk.

    Подача стала канало-независимой, и без переноса права группа «Наблюдатель»
    (куда попадают все новые пользователи) потеряла бы возможность подать заявку.
    """
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type, _ = ContentType.objects.get_or_create(app_label="contracts", model="servicerequest")
    # post_migrate ещё не создал права для новой модели, поэтому заводим явно
    new_perm, _ = Permission.objects.get_or_create(
        codename="create_service_request",
        content_type=content_type,
        defaults={"name": "Может подавать заявки подрядчику"},
    )

    old_perm = Permission.objects.filter(codename="create_okdesk_issue", content_type__app_label="integrations").first()
    if old_perm is None:
        return

    for group in Group.objects.filter(permissions=old_perm):
        group.permissions.add(new_perm)


class Migration(migrations.Migration):

    replaces = [('contracts', '0011_productioncalendarday_city_sla_standard_hours_and_more'), ('contracts', '0012_servicerequest'), ('contracts', '0013_alter_servicerequest_options_and_more'), ('contracts', '0014_workscheduleday'), ('contracts', '0015_servicerequest_act_number_servicerequest_act_scan_and_more'), ('contracts', '0016_alter_servicerequest_options'), ('contracts', '0017_servicerequestmessage_servicerequestattachment_and_more'), ('contracts', '0018_servicerequest_closing_message'), ('contracts', '0019_servicerequestsubscription'), ('contracts', '0020_contract_contractdevice_contract_and_more'), ('contracts', '0021_importsession_contract'), ('contracts', '0022_contract_vat_rate'), ('contracts', '0023_alter_servicerequest_status')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contracts', '0010_autopollcandidate'),
        ('inventory', '0022_add_hybrid_polling_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('kind', models.CharField(choices=[('holiday', 'Нерабочий праздничный день'), ('short', 'Предпраздничный сокращённый день'), ('working', 'Рабочий выходной (перенос)')], db_index=True, max_length=16, verbose_name='Тип дня')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'День производственного календаря',
                'verbose_name_plural': 'Производственный календарь',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='sla_standard_hours',
            field=models.PositiveSmallIntegerField(default=16, help_text='По ТЗ: 8 часов для городов присутствия сервисной службы, 16 — для остальных', verbose_name='Норматив устранения инцидента, рабочих часов'),
        ),
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(choices=[('Europe/Kaliningrad', 'Калининград (UTC+2)'), ('Europe/Moscow', 'Москва (UTC+3)'), ('Europe/Samara', 'Самара (UTC+4)'), ('Asia/Yekaterinburg', 'Екатеринбург (UTC+5)'), ('Asia/Omsk', 'Омск (UTC+6)'), ('Asia/Krasnoyarsk', 'Красноярск (UTC+7)'), ('Asia/Irkutsk', 'Иркутск (UTC+8)'), ('Asia/Yakutsk', 'Якутск (UTC+9)'), ('Asia/Vladivostok', 'Владивосток (UTC+10)'), ('Asia/Magadan', 'Магадан (UTC+11)'), ('Asia/Kamchatka', 'Камчатка (UTC+12)')], default='Asia/Irkutsk', max_length=32, verbose_name='Часовой пояс'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('work_start', models.TimeField(default=datetime.time(8, 0), verbose_name='Начало рабочего дня')),
                ('work_end', models.TimeField(default=datetime.time(17, 0), verbose_name='Конец рабочего дня')),
                ('weekdays', models.CharField(default='12345', help_text='Цифры дней недели без разделителей: 1 — понедельник, 7 — воскресенье. Например, 12345', max_length=7, validators=[django.core.validators.RegexValidator('^[1-7]{1,7}$', 'Цифры 1-7 без разделителей: 1 — понедельник, 7 — воскресенье')], verbose_name='Рабочие дни недели')),
                ('short_day_minutes', models.PositiveSmallIntegerField(default=60, help_text='На сколько минут раньше заканчивается рабочий день накануне праздника', verbose_name='Сокращение предпраздничного дня, мин')),
                ('is_default', models.BooleanField(default=False, help_text='Применяется, когда график не задан ни для устройства, ни для города', verbose_name='График по умолчанию')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='single_default_schedule')],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='contracts.workschedule', verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='contractdevice',
            name='work_schedule',
            field=models.ForeignKey(blank=True, help_text='Переопределяет график города, если объект работает по особому расписанию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='contracts.workschedule', verbose_name='График работы'),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_number', models.CharField(blank=True, help_text='Номер обращения в системе подрядчика: id заявки Okdesk или номер из ответного письма', max_length=64, verbose_name='Номер у подрядчика')),
                ('description', models.TextField(verbose_name='Описание заявки')),
                ('initiator_contacts', models.TextField(blank=True, help_text='Телефон инициатора и контактных лиц на объекте свободным текстом', verbose_name='Контактные данные')),
                ('registered_at', models.DateTimeField(db_index=True, verbose_name='Зарегистрирована')),
                ('stops_printing', models.BooleanField(default=True, help_text='Простой идёт в показатель доступности K1', verbose_name='Печать остановлена')),
                ('counts_in_sla', models.BooleanField(default=True, help_text='Заявка об инциденте с нормативным сроком устранения', verbose_name='Учитывать в K2')),
                ('is_critical', models.BooleanField(default=False, help_text='Норматив устранения 4 рабочих часа вместо городского', verbose_name='Критичный инцидент')),
                ('sla_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Норматив устранения, рабочих часов')),
                ('deadline_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Нормативный срок')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Работоспособность восстановлена')),
                ('closed_at', models.DateTimeField(blank=True, help_text='По ТЗ заявка выполнена только после получения скана технического акта', null=True, verbose_name='Выполнена')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('restored', 'Работоспособность восстановлена'), ('closed', 'Выполнена'), ('rejected', 'Отклонена')], db_index=True, default='open', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='contracts.contractdevice', verbose_name='Оборудование')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('reopened_from', models.ForeignKey(blank=True, help_text='При повторном обращении по тем же основаниям срок считается от первого письма', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopens', to='contracts.servicerequest', verbose_name='Переоткрытие заявки')),
                ('schedule_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='contracts.workschedule', verbose_name='График на момент подачи')),
                ('service_provider', models.ForeignKey(blank=True, help_text='Кто обслуживал устройство на момент подачи заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='contracts.serviceprovider', verbose_name='Подрядчик')),
            ],
            options={
                'verbose_name': 'Заявка подрядчику',
                'verbose_name_plural': 'Журнал заявок',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['device', '-registered_at'], name='contracts_s_device__3deb89_idx'), models.Index(fields=['status', 'deadline_at'], name='contracts_s_status_7e6a6c_idx')],
                'permissions': [('create_service_request', 'Может подавать заявки подрядчику')],
            },
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='issue_tracker',
            field=models.CharField(choices=[('okdesk', 'Okdesk (API)'), ('email', 'Письмо на почту сервис-деска'), ('none', 'Интеграция не подключена')], default='none', help_text='Через какую интеграцию подаются заявки по устройствам этого подрядчика', max_length=16, verbose_name='Приём заявок'),
        ),
        migrations.RunPython(
            code=grant_to_okdesk_groups,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('work_start', models.TimeField(verbose_name='Начало рабочего дня')),
                ('work_end', models.TimeField(verbose_name='Конец рабочего дня')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_exceptions', to='contracts.workschedule', verbose_name='График')),
            ],
            options={
                'verbose_name': 'Особый день графика',
                'verbose_name_plural': 'Особые дни графика',
                'ordering': ['schedule', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'weekday'), name='uniq_schedule_weekday')],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='act_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер технического акта'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='act_scan',
            field=models.FileField(blank=True, help_text='Приложение к письму подрядчика о восстановлении работоспособности (п. 6.6.4 ТЗ)', upload_to=contracts.models.service_act_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'tif', 'tiff'])], verbose_name='Скан технического акта'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider_downtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Простой по данным подрядчика, рабочих часов'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider_restored_at',
            field=models.DateTimeField(blank=True, help_text='Время из письма или технического акта подрядчика', null=True, verbose_name='Восстановлено по данным подрядчика'),
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-registered_at'], 'permissions': [('create_service_request', 'Может подавать заявки подрядчику'), ('close_service_request', 'Может отмечать восстановление и загружать технический акт')], 'verbose_name': 'Заявка подрядчику', 'verbose_name_plural': 'Журнал заявок'},
        ),
        migrations.CreateModel(
            name='ServiceRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('okdesk', 'Okdesk (API)'), ('email', 'Письмо на почту сервис-деска'), ('none', 'Интеграция не подключена')], db_index=True, default='email', max_length=16, verbose_name='Канал')),
                ('direction', models.CharField(choices=[('out', 'Исходящее'), ('in', 'Входящее')], db_index=True, max_length=3, verbose_name='Направление')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Message-ID письма или id комментария в системе подрядчика', max_length=255, verbose_name='Идентификатор у источника')),
                ('in_reply_to', models.CharField(blank=True, max_length=255, verbose_name='In-Reply-To')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Тема')),
                ('from_email', models.CharField(blank=True, max_length=320, verbose_name='От кого')),
                ('to_emails', models.CharField(blank=True, max_length=1000, verbose_name='Кому')),
                ('body_text', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено системой')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contracts.servicerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Сообщение по заявке',
                'verbose_name_plural': 'Переписка по заявкам',
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.models.service_mail_upload_to, verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Тип содержимого')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contracts.servicerequestmessage', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Вложение письма',
                'verbose_name_plural': 'Вложения писем',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequestmessage',
            index=models.Index(fields=['service_request', 'sent_at'], name='contracts_s_service_d68f53_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('channel', 'external_id'), name='uniq_service_message_external_id'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='closing_message',
            field=models.ForeignKey(blank=True, help_text='Заполнено, если заявку закрыло формальное письмо подрядчика, а не человек', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_requests', to='contracts.servicerequestmessage', verbose_name='Письмо о восстановлении'),
        ),
        migrations.CreateModel(
            name='ServiceRequestSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписан')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='contracts.servicerequest', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на заявку',
                'verbose_name_plural': 'Подписки на заявки',
                'constraints': [models.UniqueConstraint(fields=('user', 'service_request'), name='uniq_request_subscriber')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='Номер договора')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('price_a4_bw', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена отпечатка A4 ч/б, ₽')),
                ('price_a4_color', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена отпечатка A4 цвет, ₽')),
                ('price_a3_bw', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена отпечатка A3 ч/б, ₽')),
                ('price_a3_color', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена отпечатка A3 цвет, ₽')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.serviceprovider', verbose_name='Подрядчик')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='contractdevice',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='По какому договору обслуживается устройство — от него зависит цена отпечатка', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddIndex(
            model_name='contractdevice',
            index=models.Index(fields=['contract'], name='contracts_c_contrac_7cda58_idx'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_sessions', to='contracts.contract', verbose_name='Договор для загружаемых устройств'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20, help_text='0 — подрядчик работает без НДС', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка НДС, %'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('restored', 'Ждёт акта'), ('closed', 'Выполнена'), ('rejected', 'Отклонена')], db_index=True, default='open', max_length=16, verbose_name='Статус'),
        ),
    ]
