# Generated by Django 6.0.7 on 2026-08-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_autopollcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='issue_tracker',
            field=models.CharField(choices=[('okdesk', 'Okdesk'), ('m4', 'M4'), ('none', 'Интеграция не подключена')], default='none', help_text='Через какую интеграцию подаются заявки по устройствам этого подрядчика', max_length=16, verbose_name='Приём заявок'),
        ),
    ]
