# Generated by Django 6.0.7 on 2026-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contractsaccess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdevice',
            name='glpi_location',
            field=models.CharField(blank=True, default='', help_text='Локация из GLPI (полный путь), обновляется при проверке в GLPI', max_length=500, verbose_name='Адрес (GLPI)'),
        ),
    ]
