# Generated by Django 6.0.7 on 2026-08-18 03:46

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_service_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestattachment',
            name='okdesk_attachment_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Вложение Okdesk'),
        ),
        migrations.AddField(
            model_name='servicerequestattachment',
            name='okdesk_issue_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Заявка Okdesk'),
        ),
        migrations.AlterField(
            model_name='servicerequestattachment',
            name='file',
            field=models.FileField(blank=True, upload_to=contracts.models.service_mail_upload_to, verbose_name='Файл'),
        ),
    ]
