# Generated by Django 6.0.7 on 2026-08-18 12:34

from django.db import migrations


def grant_to_export_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type, _ = ContentType.objects.get_or_create(app_label="contracts", model="servicerequest")
    # post_migrate ещё не создал право, поэтому заводим явно
    new_perm, _ = Permission.objects.get_or_create(
        codename="export_service_requests",
        content_type=content_type,
        defaults={"name": "Может выгружать журнал заявок в Excel"},
    )

    old_perm = Permission.objects.filter(
        codename="export_contracts", content_type__app_label="contracts"
    ).first()
    if old_perm is None:
        return

    for group in Group.objects.filter(permissions=old_perm):
        group.permissions.add(new_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_attachment_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-registered_at'], 'permissions': [('create_service_request', 'Может подавать заявки подрядчику'), ('close_service_request', 'Может отмечать восстановление и загружать технический акт'), ('export_service_requests', 'Может выгружать журнал заявок в Excel')], 'verbose_name': 'Заявка подрядчику', 'verbose_name_plural': 'Журнал заявок'},
        ),
        migrations.RunPython(grant_to_export_groups, migrations.RunPython.noop),
    ]
