# Generated by Django 6.0.7 on 2026-08-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_request_export_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='issue_tracker',
            field=models.CharField(choices=[('okdesk', 'Okdesk (API)'), ('email', 'Письмо на почту сервис-деска'), ('journal', 'Только журнал — подрядчику не отправляем'), ('none', 'Интеграция не подключена')], default='none', help_text='Через какую интеграцию подаются заявки по устройствам этого подрядчика', max_length=16, verbose_name='Приём заявок'),
        ),
        migrations.AlterField(
            model_name='servicerequestmessage',
            name='channel',
            field=models.CharField(choices=[('okdesk', 'Okdesk (API)'), ('email', 'Письмо на почту сервис-деска'), ('journal', 'Только журнал — подрядчику не отправляем'), ('none', 'Интеграция не подключена')], db_index=True, default='email', max_length=16, verbose_name='Канал'),
        ),
    ]
