# Generated by Django 6.0.7 on 2026-08-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_provider_journal_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='collects_urgency',
            field=models.BooleanField(default=True, help_text='Подрядчик принимает срочность и обещает по ней норматив: поле показывается при подаче заявки и уходит ему в теле. Выключено — не спрашиваем и не передаём', verbose_name='Спрашивать срочность'),
        ),
    ]
