# Generated by Django 5.2.6 on 2025-09-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('edit_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Настройки месяца',
                'verbose_name_plural': 'Настройки месяцев',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первый день месяца (для группировки)', verbose_name='Месяц')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='№ п/п')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('branch', models.CharField(max_length=255, verbose_name='Филиал')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('equipment_model', models.CharField(max_length=255, verbose_name='Модель и наименование оборудования')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер оборудования')),
                ('inventory_number', models.CharField(max_length=100, verbose_name='Инв номер')),
                ('a4_bw_start', models.PositiveIntegerField(default=0, verbose_name='Показание счетчика А4 (ч/б) на начало периода')),
                ('a4_bw_end', models.PositiveIntegerField(default=0, verbose_name='Показание счетчика А4 (ч/б) на конец периода')),
                ('a4_color_start', models.PositiveIntegerField(default=0, verbose_name='Показание счетчика А4 (цветные) на начало периода')),
                ('a4_color_end', models.PositiveIntegerField(default=0, verbose_name='Показание счетчика А4 (цветные) на конец периода')),
                ('a3_bw_start', models.PositiveIntegerField(default=0, verbose_name='Показание счетчика А3 (ч/б) на начало периода')),
                ('a3_bw_end', models.PositiveIntegerField(default=0, verbose_name='Показание счетчика А3 (ч/б) на конец периода')),
                ('a3_color_start', models.PositiveIntegerField(default=0, verbose_name='Показание счетчика А3 (цветные) на начало периода')),
                ('a3_color_end', models.PositiveIntegerField(default=0, verbose_name='Показание счетчика А3 (цветные) на конец периода')),
                ('total_prints', models.PositiveIntegerField(default=0, verbose_name='Итого отпечатков шт.')),
                ('normative_availability', models.FloatField(default=0.0, verbose_name='Нормативное время доступности (A)')),
                ('actual_downtime', models.FloatField(default=0.0, verbose_name='Фактическое время недоступности (D)')),
                ('k1', models.FloatField(default=0.0, verbose_name='K1 = ((A - D)/A)*100%')),
                ('non_overdue_requests', models.PositiveIntegerField(default=0, verbose_name='Количество не просроченных запросов (L)')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='Общее количество запросов (W)')),
                ('k2', models.FloatField(default=0.0, verbose_name='K2 = (L/W)*100%')),
            ],
            options={
                'verbose_name': 'Ежемесячный отчёт',
                'verbose_name_plural': 'Ежемесячные отчёты',
                'permissions': [('access_monthly_report', 'Доступ к модулю ежемесячных отчётов'), ('upload_monthly_report', 'Загрузка отчётов из Excel')],
            },
        ),
    ]
