# Generated by Django 5.2.6 on 2025-09-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterModelSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, unique=True, verbose_name='Модель оборудования')),
                ('is_color', models.BooleanField(default=False, verbose_name='Цветной аппарат')),
                ('paper_format', models.CharField(choices=[('A4', 'Только A4'), ('A3', 'Только A3'), ('A4A3', 'A4 и A3')], default='A4A3', max_length=4, verbose_name='Формат бумаги')),
                ('enforce', models.BooleanField(default=True, verbose_name='Применять ограничения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правило для модели',
                'verbose_name_plural': 'Правила для моделей',
            },
        ),
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['month', 'order_number'], 'permissions': [('access_monthly_report', 'Доступ к модулю ежемесячных отчётов'), ('upload_monthly_report', 'Загрузка отчётов из Excel'), ('edit_counters_start', 'Право редактировать поля *_start'), ('edit_counters_end', 'Право редактировать поля *_end'), ('sync_from_inventory', 'Подтягивать IP/счётчики из Inventory')], 'verbose_name': 'Ежемесячный отчёт', 'verbose_name_plural': 'Ежемесячные отчёты'},
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='a3_bw_end_auto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='a3_color_end_auto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='a4_bw_end_auto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='a4_color_end_auto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес (inventory)'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='inventory_autosync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='inventory_last_ok',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный опрос (inventory)'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='a3_bw_end',
            field=models.PositiveIntegerField(default=0, verbose_name='A3 ч/б конец'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='a3_bw_start',
            field=models.PositiveIntegerField(default=0, verbose_name='A3 ч/б начало'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='a3_color_end',
            field=models.PositiveIntegerField(default=0, verbose_name='A3 цвет конец'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='a3_color_start',
            field=models.PositiveIntegerField(default=0, verbose_name='A3 цвет начало'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='a4_bw_end',
            field=models.PositiveIntegerField(default=0, verbose_name='A4 ч/б конец'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='a4_bw_start',
            field=models.PositiveIntegerField(default=0, verbose_name='A4 ч/б начало'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='a4_color_end',
            field=models.PositiveIntegerField(default=0, verbose_name='A4 цвет конец'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='a4_color_start',
            field=models.PositiveIntegerField(default=0, verbose_name='A4 цвет начало'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='equipment_model',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Модель и наименование оборудования'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='inventory_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Инв номер'),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Серийный номер оборудования'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['month', 'serial_number', 'inventory_number'], name='mr_month_sn_inv'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['month', 'inventory_number'], name='mr_month_inv'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['month', '-total_prints'], name='mr_month_total_desc'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['month', 'order_number'], name='mr_month_ord'),
        ),
    ]
