# Generated by Django 5.1 on 2025-09-08 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0002_printermodelspec_alter_monthlyreport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('excel_upload', 'Загрузка Excel'), ('bulk_sync', 'Массовая синхронизация'), ('bulk_edit', 'Массовое редактирование')], max_length=30, verbose_name='Тип операции')),
                ('records_affected', models.PositiveIntegerField(default=0, verbose_name='Затронуто записей')),
                ('fields_changed', models.JSONField(default=list, verbose_name='Измененные поля')),
                ('operation_params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('started_at', models.DateTimeField(verbose_name='Начало операции')),
                ('finished_at', models.DateTimeField(null=True, verbose_name='Конец операции')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('month', models.DateField(blank=True, null=True, verbose_name='Месяц операции')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог массовых операций',
                'verbose_name_plural': 'Логи массовых операций',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CounterChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('a4_bw_start', 'A4 ч/б начало'), ('a4_bw_end', 'A4 ч/б конец'), ('a4_color_start', 'A4 цвет начало'), ('a4_color_end', 'A4 цвет конец'), ('a3_bw_start', 'A3 ч/б начало'), ('a3_bw_end', 'A3 ч/б конец'), ('a3_color_start', 'A3 цвет начало'), ('a3_color_end', 'A3 цвет конец')], max_length=50, verbose_name='Поле')),
                ('old_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('change_source', models.CharField(choices=[('manual', 'Ручное редактирование'), ('excel_upload', 'Загрузка Excel'), ('auto_sync', 'Автосинхронизация')], default='manual', max_length=20, verbose_name='Источник')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='monthly_report.monthlyreport', verbose_name='Запись отчета')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог изменений счетчика',
                'verbose_name_plural': 'Логи изменений счетчиков',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['monthly_report', '-timestamp'], name='monthly_rep_monthly_3c2d34_idx'), models.Index(fields=['user', '-timestamp'], name='monthly_rep_user_id_a9f87d_idx'), models.Index(fields=['field_name', '-timestamp'], name='monthly_rep_field_n_cd5a75_idx')],
            },
        ),
    ]
