# Generated by Django 5.2.7 on 2025-10-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0003_bulkchangelog_counterchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='a3_bw_end_manual',
            field=models.BooleanField(default=False, verbose_name='A3 ч/б конец - ручное редактирование'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='a3_color_end_manual',
            field=models.BooleanField(default=False, verbose_name='A3 цвет конец - ручное редактирование'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='a4_bw_end_manual',
            field=models.BooleanField(default=False, verbose_name='A4 ч/б конец - ручное редактирование'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='a4_color_end_manual',
            field=models.BooleanField(default=False, verbose_name='A4 цвет конец - ручное редактирование'),
        ),
    ]
