# Generated by Claude to add is_published field to MonthControl

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0005_alter_monthlyreport_total_prints'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthcontrol',
            name='is_published',
            field=models.BooleanField(
                default=False,
                help_text='Виден всем пользователям. Неопубликованные месяцы видны только администраторам.',
                verbose_name='Опубликован'
            ),
        ),
    ]
