# Generated by Claude to add custom permissions for month visibility, auto-polling reset, and poll all printers

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0006_monthcontrol_is_published'),
    ]

    operations = [
        # Permissions are automatically created from Meta.permissions
        # This is an empty migration to track the addition of new permissions
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={
                'ordering': ['month', 'order_number'],
                'permissions': [
                    ('access_monthly_report', 'Доступ к модулю ежемесячных отчётов'),
                    ('upload_monthly_report', 'Загрузка отчётов из Excel'),
                    ('edit_counters_start', 'Право редактировать поля *_start'),
                    ('edit_counters_end', 'Право редактировать поля *_end'),
                    ('sync_from_inventory', 'Подтягивать IP/счётчики из Inventory'),
                    ('can_manage_month_visibility', 'Управление видимостью месяцев (публикация/скрытие)'),
                    ('can_reset_auto_polling', 'Возврат принтера на автоопрос'),
                    ('can_poll_all_printers', 'Опрос всех принтеров одновременно'),
                ],
                'verbose_name': 'Ежемесячный отчёт',
                'verbose_name_plural': 'Ежемесячные отчёты',
            },
        ),
    ]
