# Generated by Django 5.2.8 on 2025-12-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0009_add_can_delete_month_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthcontrol',
            name='edit_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Редактировать до'),
        ),
        migrations.AlterField(
            model_name='monthcontrol',
            name='month',
            field=models.DateField(unique=True, verbose_name='Месяц'),
        ),
    ]
