# Generated by Django 5.2.8 on 2026-01-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0010_alter_monthcontrol_edit_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkchangelog',
            name='operation_type',
            field=models.CharField(choices=[('excel_upload', 'Загрузка Excel'), ('bulk_sync', 'Массовая синхронизация'), ('bulk_edit', 'Массовое редактирование'), ('month_delete', 'Удаление месяца')], max_length=30, verbose_name='Тип операции'),
        ),
    ]
