# Generated by Django 5.2.11 on 2026-03-03 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0011_alter_bulkchangelog_operation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['month', 'order_number'], 'permissions': [('access_monthly_report', 'Доступ к модулю ежемесячных отчётов'), ('upload_monthly_report', 'Загрузка отчётов из Excel'), ('edit_counters_start', 'Право редактировать поля *_start'), ('edit_counters_end', 'Право редактировать поля *_end'), ('sync_from_inventory', 'Подтягивать IP/счётчики из Inventory'), ('view_change_history', 'Просмотр истории изменений'), ('view_monthly_report_metrics', 'Просмотр метрик автозаполнения и пользователей'), ('can_manage_month_visibility', 'Управление видимостью месяцев (публикация/скрытие)'), ('can_reset_auto_polling', 'Возврат принтера на автоопрос'), ('can_poll_all_printers', 'Опрос всех принтеров одновременно'), ('can_delete_month', 'Удаление месяца и всех связанных данных'), ('override_auto_lock', 'Игнорировать автоблокировку редактирования')], 'verbose_name': 'Ежемесячный отчёт', 'verbose_name_plural': 'Ежемесячные отчёты'},
        ),
        migrations.AddField(
            model_name='printermodelspec',
            name='allow_manual_edit',
            field=models.BooleanField(default=False, help_text='Разрешить редактирование даже при наличии автоопроса (для моделей с ненадёжным SNMP)', verbose_name='Разрешить ручное редактирование'),
        ),
        migrations.CreateModel(
            name='SerialEditOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Серийный номер')),
                ('allow_manual_edit', models.BooleanField(default=True, help_text='True = разблокировать, False = принудительно заблокировать', verbose_name='Разрешить ручное редактирование')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Если задано, override автоматически истечёт после этой даты', null=True, verbose_name='Действует до')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Исключение по серийному номеру',
                'verbose_name_plural': 'Исключения по серийным номерам',
            },
        ),
    ]
