# Generated by Django 6.0.7 on 2026-08-14 07:08

from django.db import migrations, models


def resync_metrics(apps, schema_editor):
    """Приводит уже сохранённые K1/K2 к новому правилу расчёта."""
    MonthlyReport = apps.get_model("monthly_report", "MonthlyReport")

    # Норматив доступности не задан — метрики не считались, но были записаны нулями.
    MonthlyReport.objects.filter(normative_availability__lte=0).update(k1=None, k2=None)

    # Период под SLA-учётом без заявок: K2 = 100%, а не 0%.
    MonthlyReport.objects.filter(normative_availability__gt=0, total_requests=0).update(k2=100.0)


class Migration(migrations.Migration):

    dependencies = [
        ("monthly_report", "0012_alter_monthlyreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyreport",
            name="k1",
            field=models.FloatField(blank=True, default=None, null=True, verbose_name="K1 = ((A - D)/A)*100%"),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="k2",
            field=models.FloatField(blank=True, default=None, null=True, verbose_name="K2 = (L/W)*100%"),
        ),
        migrations.RunPython(resync_metrics, migrations.RunPython.noop),
    ]
