# Generated by Django 6.0.7 on 2026-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0012_alter_monthlyreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='glpi_location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес (GLPI)'),
        ),
    ]
