# Generated by Django 5.2.1 on 2025-05-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата опроса')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка'), ('VALIDATION_ERROR', 'Ошибка валидации')], max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP-адрес')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('snmp_community', models.CharField(max_length=100, verbose_name='SNMP сообщество')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
        ),
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw_a3', models.IntegerField(blank=True, null=True, verbose_name='ЧБ A3')),
                ('bw_a4', models.IntegerField(blank=True, null=True, verbose_name='ЧБ A4')),
                ('color_a3', models.IntegerField(blank=True, null=True, verbose_name='Цвет A3')),
                ('color_a4', models.IntegerField(blank=True, null=True, verbose_name='Цвет A4')),
                ('total_pages', models.IntegerField(blank=True, null=True, verbose_name='Всего страниц')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время записи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorytask', verbose_name='Задача')),
            ],
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.printer', verbose_name='Принтер'),
        ),
    ]
