# Generated by Django 5.2.1 on 2025-05-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytask',
            options={'ordering': ['-task_timestamp'], 'verbose_name': 'Задача инвентаризации', 'verbose_name_plural': 'Задачи инвентаризации'},
        ),
        migrations.AlterModelOptions(
            name='pagecounter',
            options={'verbose_name': 'Счётчики страниц', 'verbose_name_plural': 'Счётчики страниц'},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
        migrations.AlterField(
            model_name='inventorytask',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка'), ('VALIDATION_ERROR', 'Ошибка валидации')], db_index=True, max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='inventorytask',
            name='task_timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата опроса'),
        ),
        migrations.AlterField(
            model_name='pagecounter',
            name='bw_a3',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ЧБ A3'),
        ),
        migrations.AlterField(
            model_name='pagecounter',
            name='bw_a4',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ЧБ A4'),
        ),
        migrations.AlterField(
            model_name='pagecounter',
            name='color_a3',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Цвет A3'),
        ),
        migrations.AlterField(
            model_name='pagecounter',
            name='color_a4',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Цвет A4'),
        ),
        migrations.AlterField(
            model_name='pagecounter',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='pagecounter',
            name='total_pages',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Всего страниц'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Серийный номер'),
        ),
        migrations.AddIndex(
            model_name='inventorytask',
            index=models.Index(fields=['printer'], name='inventory_i_printer_d7ef6f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytask',
            index=models.Index(fields=['status'], name='inventory_i_status_985705_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytask',
            index=models.Index(fields=['task_timestamp'], name='inventory_i_task_ti_31916b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytask',
            index=models.Index(fields=['printer', 'task_timestamp'], name='inventory_i_printer_a173b6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytask',
            index=models.Index(fields=['status', 'task_timestamp'], name='inventory_i_status_dfe14c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecounter',
            index=models.Index(fields=['task'], name='inventory_p_task_id_8e734b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecounter',
            index=models.Index(fields=['total_pages'], name='inventory_p_total_p_d0f84f_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecounter',
            index=models.Index(fields=['recorded_at'], name='inventory_p_recorde_7c407c_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['ip_address'], name='inventory_p_ip_addr_20a794_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['serial_number'], name='inventory_p_serial__9c987e_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['model'], name='inventory_p_model_835177_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['last_updated'], name='inventory_p_last_up_928ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['model', 'serial_number'], name='inventory_p_model_b75573_idx'),
        ),
    ]
