# Generated by Django 5.2.1 on 2025-06-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventorytask_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumableStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drum_black",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Драм K"
                    ),
                ),
                (
                    "drum_cyan",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Драм C"
                    ),
                ),
                (
                    "drum_magenta",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Драм M"
                    ),
                ),
                (
                    "drum_yellow",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Драм Y"
                    ),
                ),
                (
                    "fuserkit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Печь"
                    ),
                ),
                (
                    "toner_black",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Тонер K"
                    ),
                ),
                (
                    "toner_cyan",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Тонер C"
                    ),
                ),
                (
                    "toner_magenta",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Тонер M"
                    ),
                ),
                (
                    "toner_yellow",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Тонер Y"
                    ),
                ),
                (
                    "transferkit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Трансфер"
                    ),
                ),
                (
                    "wastetoner",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Бункер"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время записи"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventorytask",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расходники",
                "verbose_name_plural": "Расходники",
                "indexes": [
                    models.Index(
                        fields=["task"], name="inventory_c_task_id_2c6ad6_idx"
                    ),
                    models.Index(
                        fields=["recorded_at"], name="inventory_c_recorde_3179f8_idx"
                    ),
                ],
            },
        ),
    ]
