# Generated by Django 5.2.1 on 2025-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorytask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecounter',
            options={'verbose_name': 'Счётчики и расходники', 'verbose_name_plural': 'Счётчики и расходники'},
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='drum_black',
            field=models.CharField(blank=True, max_length=20, verbose_name='DRUMBLACK'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='drum_cyan',
            field=models.CharField(blank=True, max_length=20, verbose_name='DRUMCYAN'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='drum_magenta',
            field=models.CharField(blank=True, max_length=20, verbose_name='DRUMMAGENTA'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='drum_yellow',
            field=models.CharField(blank=True, max_length=20, verbose_name='DRUMYELLOW'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='fuser_kit',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('WARNING', 'WARNING')], max_length=20, verbose_name='FUSERKIT'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='toner_black',
            field=models.CharField(blank=True, max_length=20, verbose_name='TONERBLACK'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='toner_cyan',
            field=models.CharField(blank=True, max_length=20, verbose_name='TONERCYAN'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='toner_magenta',
            field=models.CharField(blank=True, max_length=20, verbose_name='TONERMAGENTA'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='toner_yellow',
            field=models.CharField(blank=True, max_length=20, verbose_name='TONERYELLOW'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='transfer_kit',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('WARNING', 'WARNING')], max_length=20, verbose_name='TRANSFERKIT'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='waste_toner',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('WARNING', 'WARNING')], max_length=20, verbose_name='WASTETONER'),
        ),
    ]
