# Generated by Django 5.2.1 on 2025-08-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_organization_printer_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytask',
            name='match_rule',
            field=models.CharField(blank=True, choices=[('SN_MAC', 'Серийник + MAC'), ('MAC_ONLY', 'Только MAC'), ('SN_ONLY', 'Только серийник')], db_index=True, max_length=10, null=True, verbose_name='Правило сопоставления'),
        ),
        migrations.AddField(
            model_name='printer',
            name='last_match_rule',
            field=models.CharField(blank=True, choices=[('SN_MAC', 'Серийник + MAC'), ('MAC_ONLY', 'Только MAC'), ('SN_ONLY', 'Только серийник')], db_index=True, max_length=10, null=True, verbose_name='Последнее правило сопоставления'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['last_match_rule'], name='inventory_p_last_ma_53deaa_idx'),
        ),
    ]
