# Generated by Django 5.2.1 on 2025-09-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorytask_match_rule_printer_last_match_rule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_inventory_app', 'Can access Inventory app'), ('run_inventory', 'Can run inventory scans'), ('export_printers', 'Can export printers to Excel'), ('export_amb_report', 'Can export AMB report')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
