# Generated by Django 5.2.6 on 2025-09-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytask',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка'), ('VALIDATION_ERROR', 'Ошибка валидации'), ('HISTORICAL_INCONSISTENCY', 'Исторические данные не согласованы')], db_index=True, max_length=30, verbose_name='Статус'),
        ),
    ]
