# Generated by Django 5.2.7 on 2025-10-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventorytask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytask',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка'), ('VALIDATION_ERROR', 'Ошибка валидации')], db_index=True, max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='inventorytask',
            index=models.Index(fields=['printer', 'status', '-task_timestamp'], name='inv_task_printer_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['organization', 'ip_address'], name='inv_printer_org_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['last_match_rule', 'ip_address'], name='inv_printer_rule_ip_idx'),
        ),
    ]
