# Generated by Django 5.2.7 on 2025-10-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_cartridge_devicemodelcartridge'),
        ('inventory', '0009_alter_inventorytask_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='device_model',
            field=models.ForeignKey(blank=True, help_text='Модель из справочника contracts', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_printers', to='contracts.devicemodel', verbose_name='Модель оборудования'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.CharField(blank=True, db_index=True, help_text='Устаревшее текстовое поле. Используйте device_model.', max_length=200, verbose_name='Модель (текст, устарело)'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['device_model', 'ip_address'], name='inv_printer_devmodel_ip_idx'),
        ),
    ]
