# Generated by Django 5.2.7 on 2025-11-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_cartridge_devicemodelcartridge'),
        ('inventory', '0010_register_existing_device_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['device_model', 'ip_address'], name='inv_printer_devmodel_ip_idx'),
        ),
    ]
