# Generated by Django 5.2.7 on 2025-11-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_printer_inv_printer_devmodel_ip_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='polling_method',
            field=models.CharField(choices=[('SNMP', 'SNMP (GLPI Agent)'), ('WEB', 'Web Parsing')], default='SNMP', max_length=10, verbose_name='Метод опроса'),
        ),
        migrations.AddField(
            model_name='printer',
            name='web_password',
            field=models.CharField(blank=True, help_text='Для веб-парсинга (если требуется аутентификация)', max_length=100, verbose_name='Web пароль'),
        ),
        migrations.AddField(
            model_name='printer',
            name='web_username',
            field=models.CharField(blank=True, help_text='Для веб-парсинга (если требуется аутентификация)', max_length=100, verbose_name='Web логин'),
        ),
        migrations.CreateModel(
            name='WebParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=10, verbose_name='Протокол')),
                ('url_path', models.CharField(help_text='Например: /status.htm или /eng/general/information.cgi', max_length=500, verbose_name='URL путь')),
                ('field_name', models.CharField(choices=[('serial_number', 'Серийный номер'), ('mac_address', 'MAC-адрес'), ('counter', 'Общий счетчик'), ('counter_a4_bw', 'ЧБ A4'), ('counter_a3_bw', 'ЧБ A3'), ('counter_a4_color', 'Цвет A4'), ('counter_a3_color', 'Цвет A3'), ('toner_black', 'Тонер черный'), ('toner_cyan', 'Тонер голубой'), ('toner_magenta', 'Тонер пурпурный'), ('toner_yellow', 'Тонер желтый'), ('drum_black', 'Барабан черный'), ('drum_cyan', 'Барабан голубой'), ('drum_magenta', 'Барабан пурпурный'), ('drum_yellow', 'Барабан желтый')], max_length=50, verbose_name='Поле')),
                ('xpath', models.CharField(blank=True, help_text='Например: //td[contains(text(),"Serial")]/following-sibling::td/text()', max_length=500, verbose_name='XPath выражение')),
                ('regex_pattern', models.CharField(blank=True, help_text='Для обработки извлеченного значения', max_length=500, verbose_name='Regex паттерн')),
                ('regex_replacement', models.CharField(blank=True, max_length=500, verbose_name='Regex замена')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='Вычисляемое поле')),
                ('source_rules', models.TextField(blank=True, help_text='JSON список ID правил для вычисления', verbose_name='Правила-источники')),
                ('calculation_formula', models.TextField(blank=True, help_text='Например: rule_1 + rule_2 * 2', verbose_name='Формула вычисления')),
                ('actions_chain', models.TextField(blank=True, help_text='JSON список действий перед парсингом', verbose_name='Цепочка действий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_parsing_rules', to='inventory.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Правило веб-парсинга',
                'verbose_name_plural': 'Правила веб-парсинга',
                'ordering': ['printer', 'field_name'],
            },
        ),
    ]
