# Generated by Django 5.2.7 on 2025-11-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_printer_polling_method_printer_web_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_inventory_app', 'Can access Inventory app'), ('run_inventory', 'Can run inventory scans'), ('export_printers', 'Can export printers to Excel'), ('export_amb_report', 'Can export AMB report'), ('manage_web_parsing', 'Can manage web parsing rules'), ('view_web_parsing', 'Can view web parsing rules')]},
        ),
    ]
