# Generated by Django 5.2.7 on 2025-11-04 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_cartridge_devicemodelcartridge'),
        ('inventory', '0013_alter_inventoryaccess_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_inventory_app', 'Can access Inventory app'), ('run_inventory', 'Can run inventory scans'), ('export_printers', 'Can export printers to Excel'), ('export_amb_report', 'Can export AMB report'), ('manage_web_parsing', 'Can manage web parsing rules'), ('view_web_parsing', 'Can view web parsing rules'), ('can_create_public_templates', 'Can create public parsing templates')]},
        ),
        migrations.CreateModel(
            name='WebParsingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Ricoh MP C2004 - стандартная настройка"', max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, help_text='Комментарии по настройке', verbose_name='Описание')),
                ('rules_config', models.JSONField(help_text='JSON массив с правилами парсинга', verbose_name='Конфигурация правил')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_public', models.BooleanField(default=False, help_text='Доступен всем пользователям', verbose_name='Публичный')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Количество применений')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('device_model', models.ForeignKey(help_text='К какой модели относится этот шаблон', on_delete=django.db.models.deletion.CASCADE, related_name='parsing_templates', to='contracts.devicemodel', verbose_name='Модель оборудования')),
            ],
            options={
                'verbose_name': 'Шаблон веб-парсинга',
                'verbose_name_plural': 'Шаблоны веб-парсинга',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_model', 'is_public'], name='inventory_w_device__fee9fb_idx')],
            },
        ),
    ]
