# Generated by Django 5.2.11 on 2026-02-25 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_devicemodel_has_network_port'),
        ('inventory', '0015_alter_inventorytask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ip_change', 'Смена IP-адреса'), ('serial_update', 'Обновление серийника'), ('mac_update', 'Обновление MAC-адреса'), ('deactivation', 'Деактивация'), ('replacement', 'Замена оборудования'), ('activation', 'Активация')], db_index=True, max_length=20, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Новые значения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('triggered_by', models.CharField(choices=[('auto_poll', 'Автоопрос'), ('manual', 'Вручную')], default='auto_poll', max_length=20, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Лог изменений принтера',
                'verbose_name_plural': 'Логи изменений принтеров',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='printer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Неактивные принтеры - это замененное или снятое оборудование', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='printer',
            name='replaced_at',
            field=models.DateTimeField(blank=True, help_text='Когда принтер был заменён другим оборудованием', null=True, verbose_name='Дата замены'),
        ),
        migrations.AddField(
            model_name='printer',
            name='replaced_by',
            field=models.ForeignKey(blank=True, help_text='Принтер, который заменил данный', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_printers', to='inventory.printer', verbose_name='Заменён на'),
        ),
        # AlterField завёрнут в SeparateDatabaseAndState, чтобы безопасно удалить
        # уникальное ограничение/индекс независимо от его имени в БД.
        # Проблема: БД могла быть мигрирована из SQLite, где constraint назывался
        # idx_16676_sqlite_autoindex_inventory_printer_1 и является INDEX-ом,
        # а не CONSTRAINT-ом — стандартный ALTER TABLE ... DROP CONSTRAINT падает.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    DECLARE
                        cname text;
                        iname text;
                    BEGIN
                        -- Сначала ищем constraint в pg_constraint
                        SELECT c.conname INTO cname
                        FROM pg_constraint c
                        JOIN pg_class t ON t.oid = c.conrelid
                        WHERE t.relname = 'inventory_printer'
                          AND c.contype = 'u'
                          AND array_length(c.conkey, 1) = 1
                          AND c.conkey[1] = (
                              SELECT attnum FROM pg_attribute
                              WHERE attrelid = 'inventory_printer'::regclass
                                AND attname = 'ip_address'
                          )
                        LIMIT 1;
                        IF cname IS NOT NULL THEN
                            EXECUTE format('ALTER TABLE inventory_printer DROP CONSTRAINT %I', cname);
                            RETURN;
                        END IF;
                        -- Если constraint не нашли, ищем уникальный индекс напрямую
                        SELECT i.relname INTO iname
                        FROM pg_index ix
                        JOIN pg_class t ON t.oid = ix.indrelid
                        JOIN pg_class i ON i.oid = ix.indexrelid
                        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ix.indkey[0]
                        WHERE t.relname = 'inventory_printer'
                          AND ix.indisunique = true
                          AND a.attname = 'ip_address'
                          AND array_length(ix.indkey::int[], 1) = 1
                          AND NOT EXISTS (
                              SELECT 1 FROM pg_constraint WHERE conindid = ix.indexrelid
                          )
                        LIMIT 1;
                        IF iname IS NOT NULL THEN
                            EXECUTE format('DROP INDEX IF EXISTS %I', iname);
                        END IF;
                    END;
                    $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='printer',
                    name='ip_address',
                    field=models.GenericIPAddressField(db_index=True, verbose_name='IP-адрес'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    DECLARE
                        cname text;
                        iname text;
                    BEGIN
                        SELECT c.conname INTO cname
                        FROM pg_constraint c
                        JOIN pg_class t ON t.oid = c.conrelid
                        WHERE t.relname = 'inventory_printer'
                          AND c.contype = 'u'
                          AND array_length(c.conkey, 1) = 1
                          AND c.conkey[1] = (
                              SELECT attnum FROM pg_attribute
                              WHERE attrelid = 'inventory_printer'::regclass
                                AND attname = 'mac_address'
                          )
                        LIMIT 1;
                        IF cname IS NOT NULL THEN
                            EXECUTE format('ALTER TABLE inventory_printer DROP CONSTRAINT %I', cname);
                            RETURN;
                        END IF;
                        SELECT i.relname INTO iname
                        FROM pg_index ix
                        JOIN pg_class t ON t.oid = ix.indrelid
                        JOIN pg_class i ON i.oid = ix.indexrelid
                        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ix.indkey[0]
                        WHERE t.relname = 'inventory_printer'
                          AND ix.indisunique = true
                          AND a.attname = 'mac_address'
                          AND array_length(ix.indkey::int[], 1) = 1
                          AND NOT EXISTS (
                              SELECT 1 FROM pg_constraint WHERE conindid = ix.indexrelid
                          )
                        LIMIT 1;
                        IF iname IS NOT NULL THEN
                            EXECUTE format('DROP INDEX IF EXISTS %I', iname);
                        END IF;
                    END;
                    $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='printer',
                    name='mac_address',
                    field=models.CharField(blank=True, db_index=True, max_length=17, null=True, verbose_name='MAC-адрес'),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['is_active', 'ip_address'], name='inv_printer_active_ip_idx'),
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('ip_address',), name='unique_active_ip'),
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('mac_address', None), _negated=True), models.Q(('mac_address', ''), _negated=True)), fields=('mac_address',), name='unique_active_mac'),
        ),
        migrations.AddField(
            model_name='printerchangelog',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='inventory.printer', verbose_name='Принтер'),
        ),
        migrations.AddField(
            model_name='printerchangelog',
            name='related_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_changes', to='inventory.printer', verbose_name='Связанный принтер'),
        ),
        migrations.AddIndex(
            model_name='printerchangelog',
            index=models.Index(fields=['printer', '-timestamp'], name='inventory_p_printer_673f01_idx'),
        ),
        migrations.AddIndex(
            model_name='printerchangelog',
            index=models.Index(fields=['action', '-timestamp'], name='inventory_p_action_f10c88_idx'),
        ),
        migrations.AddIndex(
            model_name='printerchangelog',
            index=models.Index(fields=['related_printer', '-timestamp'], name='inventory_p_related_ff62b6_idx'),
        ),
    ]
