# Generated by Django 5.2.11 on 2026-03-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_printerchangelog_printer_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webparsingrule",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("serial_number", "Серийный номер"),
                    ("mac_address", "MAC-адрес"),
                    ("counter", "Общий счетчик"),
                    ("counter_a4_bw", "ЧБ A4"),
                    ("counter_a3_bw", "ЧБ A3"),
                    ("counter_a4_color", "Цвет A4"),
                    ("counter_a3_color", "Цвет A3"),
                    ("toner_black", "Тонер черный"),
                    ("toner_cyan", "Тонер голубой"),
                    ("toner_magenta", "Тонер пурпурный"),
                    ("toner_yellow", "Тонер желтый"),
                    ("drum_black", "Барабан черный"),
                    ("drum_cyan", "Барабан голубой"),
                    ("drum_magenta", "Барабан пурпурный"),
                    ("drum_yellow", "Барабан желтый"),
                    ("variable_1", "Переменная 1"),
                    ("variable_2", "Переменная 2"),
                    ("variable_3", "Переменная 3"),
                    ("variable_4", "Переменная 4"),
                    ("variable_5", "Переменная 5"),
                ],
                max_length=50,
                verbose_name="Поле",
            ),
        ),
    ]
