# Generated by Django 5.2.11 on 2026-06-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_unique_active_usb_serial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryaccess",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("access_inventory_app", "Can access Inventory app"),
                    ("run_inventory", "Can run inventory scans"),
                    ("export_printers", "Can export printers to Excel"),
                    ("export_amb_report", "Can export AMB report"),
                    ("manage_web_parsing", "Can manage web parsing rules"),
                    ("view_web_parsing", "Can view web parsing rules"),
                    ("can_create_public_templates", "Can create public parsing templates"),
                    ("view_api_docs", "Can view API documentation"),
                ],
            },
        ),
    ]
