# Generated by Django 5.2.11 on 2026-06-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_alter_inventoryaccess_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="polling_method",
            field=models.CharField(
                choices=[
                    ("SNMP", "SNMP (GLPI Agent)"),
                    ("WEB", "Web Parsing"),
                    ("USB_API", "USB Agent (API)"),
                    ("HYBRID", "Совмещённый (SNMP + Web)"),
                ],
                default="SNMP",
                max_length=10,
                verbose_name="Метод опроса",
            ),
        ),
    ]
