# Generated by Django 6.0.7 on 2026-09-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_add_hybrid_polling_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
    ]
