# Generated by Django 5.2.8 on 2026-01-10 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glpisync',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время проверки'),
        ),
    ]
