# Generated by Django 5.2.9 on 2025-12-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="glpisync",
            new_name="integration_contrac_c6181f_idx",
            old_name="integration_contrac_5dc1ef_idx",
        ),
        migrations.RenameIndex(
            model_name="glpisync",
            new_name="integration_status_a7c2b1_idx",
            old_name="integration_status_8bb1b9_idx",
        ),
        migrations.RenameIndex(
            model_name="glpisync",
            new_name="integration_searche_3bdf27_idx",
            old_name="integration_searche_3e64f3_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationlog",
            new_name="integration_system_29906e_idx",
            old_name="integration_system_d0d8a1_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationlog",
            new_name="integration_level_a81e3a_idx",
            old_name="integration_level_8bb6c7_idx",
        ),
        migrations.AddField(
            model_name="glpisync",
            name="glpi_state_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID состояния устройства (например: в работе, сломан, в ремонте)",
                null=True,
                verbose_name="ID состояния в GLPI",
            ),
        ),
        migrations.AddField(
            model_name="glpisync",
            name="glpi_state_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Название состояния устройства в GLPI",
                max_length=255,
                verbose_name="Состояние в GLPI",
            ),
        ),
    ]
