# Generated by Django 5.2.11 on 2026-03-18 04:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_devicemodel_has_network_port"),
        ("integrations", "0002_alter_glpisync_checked_at"),
        ("inventory", "0017_alter_webparsingrule_field_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GLPICrossCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("OFFLINE", "Офлайн принтер"), ("UNPOLLED", "Не опрашивается")],
                        max_length=10,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GLPI_ACTIVE", "Активен в GLPI"),
                            ("GLPI_STALE", "Устаревшие данные в GLPI"),
                            ("NOT_FOUND", "Не найден в GLPI"),
                            ("NO_SERIAL", "Нет серийного номера"),
                            ("ERROR", "Ошибка проверки"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("serial_number", models.CharField(blank=True, max_length=255, verbose_name="Серийный номер")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-адрес")),
                ("organization_name", models.CharField(blank=True, max_length=255, verbose_name="Организация")),
                ("glpi_printer_id", models.IntegerField(blank=True, null=True, verbose_name="ID принтера в GLPI")),
                ("glpi_name", models.CharField(blank=True, max_length=255, verbose_name="Имя в GLPI")),
                (
                    "glpi_last_pages_counter",
                    models.IntegerField(blank=True, null=True, verbose_name="Счётчик страниц в GLPI"),
                ),
                ("glpi_date_mod", models.DateTimeField(blank=True, null=True, verbose_name="Дата обновления в GLPI")),
                (
                    "glpi_state_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Состояние в GLPI"),
                ),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Время проверки")),
                (
                    "batch_id",
                    models.CharField(blank=True, db_index=True, max_length=50, verbose_name="ID пакета проверки"),
                ),
                (
                    "contract_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glpi_cross_checks",
                        to="contracts.contractdevice",
                        verbose_name="Устройство в договоре",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glpi_cross_checks",
                        to="inventory.printer",
                        verbose_name="Принтер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кросс-проверка GLPI",
                "verbose_name_plural": "Кросс-проверки GLPI",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(fields=["batch_id"], name="integration_batch_i_1ac1a3_idx"),
                    models.Index(fields=["category", "status"], name="integration_categor_60f3ae_idx"),
                ],
            },
        ),
    ]
