# Generated by Django 5.2.11 on 2026-03-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_glpicrosscheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="OkdeskIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issue_id", models.IntegerField(unique=True, verbose_name="ID заявки в Okdesk")),
                ("title", models.CharField(max_length=500, verbose_name="Заголовок")),
                ("created_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата создания")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения")),
                ("status_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Статус")),
                ("priority_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Приоритет")),
                ("assignee_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Исполнитель")),
                ("company_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Компания")),
                (
                    "serial_numbers",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Через запятую, как в исходной БД Okdesk",
                        verbose_name="Серийные номера",
                    ),
                ),
                ("is_overdue", models.BooleanField(default=False, verbose_name="Просрочена")),
            ],
            options={
                "verbose_name": "Заявка Okdesk",
                "verbose_name_plural": "Заявки Okdesk",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="integration_created_05a6cb_idx"),
                    models.Index(fields=["status_name"], name="integration_status__17a32b_idx"),
                ],
            },
        ),
    ]
