# Generated by Django 5.2.11 on 2026-03-25 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_okdeskissue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="okdeskissue",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал",
            ),
        ),
        migrations.AddField(
            model_name="okdeskissue",
            name="source",
            field=models.CharField(
                choices=[
                    ("import", "Импорт из SQLite"),
                    ("created", "Создана через сайт"),
                    ("sync", "Синхронизация API"),
                ],
                default="import",
                max_length=10,
                verbose_name="Источник",
            ),
        ),
        migrations.AddField(
            model_name="okdeskissue",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последняя синхронизация"),
        ),
        migrations.AddIndex(
            model_name="okdeskissue",
            index=models.Index(fields=["source"], name="integration_source_7a6bb0_idx"),
        ),
    ]
