# Generated by Django 5.2.11 on 2026-03-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_okdeskissue_created_by_okdeskissue_source_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="okdeskissue",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_okdesk_issues", "Просмотр заявок Okdesk"),
                    ("create_okdesk_issue", "Создание заявок в Okdesk"),
                    ("manage_okdesk_token", "Управление токеном Okdesk"),
                ],
                "verbose_name": "Заявка Okdesk",
                "verbose_name_plural": "Заявки Okdesk",
            },
        ),
    ]
