# Generated by Django 5.2.11 on 2026-03-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_add_okdesk_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="okdeskissue",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
        ),
    ]
