# Generated by Django 5.2.11 on 2026-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_okdeskissue_deadline_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="okdeskissue",
            name="author_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Автор заявки"),
        ),
    ]
