# Generated by Django 5.2.11 on 2026-05-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_devicemodel_has_network_port"),
        ("integrations", "0008_add_author_name_to_okdeskissue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="okdeskissue",
            name="contract_device",
            field=models.ForeignKey(
                blank=True,
                help_text="Конкретное устройство, к которому привязана эта строка заявки. Если у заявки несколько серийников — создаётся по строке на каждое найденное устройство.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="okdesk_issues",
                to="contracts.contractdevice",
                verbose_name="Устройство в договоре",
            ),
        ),
        migrations.AlterField(
            model_name="okdeskissue",
            name="issue_id",
            field=models.IntegerField(verbose_name="ID заявки в Okdesk"),
        ),
        migrations.AddIndex(
            model_name="okdeskissue",
            index=models.Index(fields=["issue_id"], name="integration_issue_i_dc21d0_idx"),
        ),
        migrations.AddIndex(
            model_name="okdeskissue",
            index=models.Index(fields=["contract_device"], name="integration_contrac_c895f9_idx"),
        ),
        migrations.AddConstraint(
            model_name="okdeskissue",
            constraint=models.UniqueConstraint(
                fields=("issue_id", "contract_device"), name="uniq_okdeskissue_issue_device"
            ),
        ),
        migrations.AddConstraint(
            model_name="okdeskissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("contract_device__isnull", True)),
                fields=("issue_id",),
                name="uniq_okdeskissue_issue_orphan",
            ),
        ),
    ]
