# Generated by Django 6.0.5 on 2026-05-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_okdesk_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okdeskissue',
            options={'ordering': ['-created_at'], 'permissions': [('view_okdesk_issues', 'Просмотр заявок Okdesk'), ('create_okdesk_issue', 'Создание заявок в Okdesk'), ('manage_okdesk_token', 'Управление токеном Okdesk'), ('post_okdesk_comment', 'Отправка комментариев в Okdesk')], 'verbose_name': 'Заявка Okdesk', 'verbose_name_plural': 'Заявки Okdesk'},
        ),
    ]
