# Generated by Django 6.0.7 on 2026-08-29 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_autopollcandidate'),
        ('integrations', '0012_add_post_comment_perm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OkdeskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(help_text='Например: https://abikom.okdesk.ru/api/v1', verbose_name='API URL')),
                ('encrypted_token', models.TextField(blank=True, default='', help_text='Используется фоновой синхронизацией заявок и комментариев', verbose_name='Зашифрованный системный API-токен')),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='Проверять SSL-сертификат')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Инстанс Okdesk',
                'verbose_name_plural': 'Инстансы Okdesk',
                'ordering': ['service_provider__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='okdeskissue',
            name='uniq_okdeskissue_issue_device',
        ),
        migrations.RemoveConstraint(
            model_name='okdeskissue',
            name='uniq_okdeskissue_issue_orphan',
        ),
        migrations.RemoveIndex(
            model_name='okdeskcomment',
            name='integration_issue_i_cea7d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='okdeskissue',
            name='integration_issue_i_dc21d0_idx',
        ),
        migrations.AlterField(
            model_name='okdeskcomment',
            name='comment_id',
            field=models.IntegerField(db_index=True, verbose_name='ID комментария в Okdesk'),
        ),
        migrations.AddField(
            model_name='okdeskinstance',
            name='service_provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='okdesk_instance', to='contracts.serviceprovider', verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='okdeskcomment',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='integrations.okdeskinstance', verbose_name='Инстанс Okdesk'),
        ),
        migrations.AddField(
            model_name='okdeskissue',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='integrations.okdeskinstance', verbose_name='Инстанс Okdesk'),
        ),
        migrations.AddIndex(
            model_name='okdeskcomment',
            index=models.Index(fields=['instance', 'issue_id', '-created_at'], name='integration_instanc_6959ea_idx'),
        ),
        migrations.AddIndex(
            model_name='okdeskissue',
            index=models.Index(fields=['instance', 'issue_id'], name='integration_instanc_ebce68_idx'),
        ),
        migrations.AddConstraint(
            model_name='okdeskcomment',
            constraint=models.UniqueConstraint(fields=('instance', 'comment_id'), name='uniq_okdeskcomment_instance_comment'),
        ),
        migrations.AddConstraint(
            model_name='okdeskissue',
            constraint=models.UniqueConstraint(fields=('instance', 'issue_id', 'contract_device'), name='uniq_okdeskissue_issue_device'),
        ),
        migrations.AddConstraint(
            model_name='okdeskissue',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_device__isnull', True)), fields=('instance', 'issue_id'), name='uniq_okdeskissue_issue_orphan'),
        ),
    ]
