# Generated by Django 6.0.7 on 2026-08-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_add_post_comment_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='okdeskissue',
            name='journal_excluded',
            field=models.BooleanField(default=False, help_text='Синк журнала пропускает такие заявки. Ставится автоматически, если Okdesk отдаёт 403 (доступ к заявке ограничен), или вручную для неважных.', verbose_name='Не переносить в журнал заявок'),
        ),
    ]
