# Generated by Django 6.0.7 on 2026-08-25 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_serviceprovider_issue_tracker'),
        ('integrations', '0012_add_post_comment_perm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M4Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(help_text='Единый URL api.php: у M4 все методы уходят на него. Выдаёт подрядчик', verbose_name='Адрес сервис-деска')),
                ('encrypted_token', models.TextField(blank=True, default='', verbose_name='Зашифрованный токен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='m4_connection', to='contracts.serviceprovider', verbose_name='Подрядчик')),
            ],
            options={
                'verbose_name': 'Подключение к M4',
                'verbose_name_plural': 'Подключения к M4',
            },
        ),
        migrations.CreateModel(
            name='M4Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID заявки в M4')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('status_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Статус')),
                ('serial_number', models.CharField(blank=True, default='', max_length=128, verbose_name='Серийный номер')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('author_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Автор заявки')),
                ('contract_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m4_issues', to='contracts.contractdevice', verbose_name='Устройство в договоре')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Заявка M4',
                'verbose_name_plural': 'Заявки M4',
                'ordering': ['-created_at'],
                'permissions': [('manage_m4_token', 'Управление токеном M4')],
                'indexes': [models.Index(fields=['-created_at'], name='integration_created_015472_idx'), models.Index(fields=['contract_device'], name='integration_contrac_edef10_idx')],
            },
        ),
    ]
