# Generated by Django 6.0.7 on 2026-09-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_okdesk_instance_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='okdeskinstance',
            name='issue_custom_params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: код атрибута Okdesk → шаблон значения. Коды — GET /issues/parameters/list. Плейсхолдеры: {serial} {manufacturer} {model} {org} {city} {address} {room} {service_type} {cartridge} {comment} {phone} {fio}. Пример: {"serialnumber": "{serial}", "model": "{manufacturer} {model}"}', verbose_name='Доп. атрибуты заявки (custom_parameters)'),
        ),
    ]
