# Generated by Django 6.0.7 on 2026-10-05 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_okdeskinstance_issue_custom_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkdeskEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.IntegerField(verbose_name='ID оборудования в Okdesk')),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Инвентарный номер')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Компания')),
                ('maintenance_entity_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Площадка')),
                ('kind_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип оборудования')),
                ('manufacturer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Производитель')),
                ('model_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Модель')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ API')),
                ('synced_at', models.DateTimeField(verbose_name='Последняя синхронизация')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='integrations.okdeskinstance', verbose_name='Инстанс Okdesk')),
            ],
            options={
                'verbose_name': 'Оборудование Okdesk',
                'verbose_name_plural': 'Оборудование Okdesk',
                'ordering': ['company_name', 'model_name'],
                'indexes': [models.Index(fields=['instance', 'serial_number'], name='integration_instanc_0c7f7c_idx')],
                'constraints': [models.UniqueConstraint(fields=('instance', 'equipment_id'), name='uniq_okdeskequipment_instance_equipment')],
            },
        ),
    ]
