# Generated by Django 6.0.7 on 2026-10-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_okdeskequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='okdeskinstance',
            name='encrypted_staff_token',
            field=models.TextField(blank=True, default='', help_text='Токен учётки сотрудника подрядчика — только для чтения справочника оборудования (/equipments): клиентский токен туда не пускает, а сотруднический не видит заявки клиента. Пусто — используется системный.', verbose_name='Зашифрованный API-токен сотрудника'),
        ),
    ]
