# Generated by Django 5.2.7 on 2025-10-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Точное совпадение с preferred_username из Keycloak', max_length=150, unique=True, verbose_name='Логин пользователя')),
                ('email', models.EmailField(blank=True, help_text='Для справки, не используется при проверке', max_length=254, verbose_name='Email (опционально)')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО (опционально)')),
                ('is_active', models.BooleanField(default=True, help_text='Можно временно отключить доступ без удаления', verbose_name='Активен')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('added_by', models.CharField(blank=True, max_length=150, verbose_name='Добавил')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Разрешенный пользователь',
                'verbose_name_plural': 'Разрешенные пользователи',
                'ordering': ['username'],
            },
        ),
    ]
