# Generated by Django 5.2.8 on 2026-01-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_userthemepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthemepreference',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('system', 'Системная')], default='light', max_length=10, verbose_name='Тема'),
        ),
    ]
