# Generated by Django 5.2.8 on 2026-01-21 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_userthemepreference_theme'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Словарь {поле: {old: старое, new: новое}}', verbose_name='Изменения')),
                ('object_repr', models.CharField(blank=True, help_text='Строковое представление объекта на момент изменения', max_length=500, verbose_name='Представление объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог изменений',
                'verbose_name_plural': 'Логи изменений',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='access_enti_content_232257_idx'), models.Index(fields=['user', 'timestamp'], name='access_enti_user_id_27b0e7_idx'), models.Index(fields=['action', 'timestamp'], name='access_enti_action_4612dc_idx')],
            },
        ),
    ]
