# Generated by Django 5.2.8 on 2026-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_entitychangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_entity_changes', 'Просмотр истории изменений')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
