# Generated by Django 6.0.7 on 2026-08-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_add_user_profile'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alloweduser',
            options={'ordering': ['username'], 'permissions': [('manage_users', 'Управление пользователями и правами')], 'verbose_name': 'Разрешенный пользователь', 'verbose_name_plural': 'Разрешенные пользователи'},
        ),
        migrations.AddField(
            model_name='alloweduser',
            name='initial_groups',
            field=models.ManyToManyField(blank=True, help_text='Выдаются при создании Django-пользователя. Дальше права живут на самом пользователе.', to='auth.group', verbose_name='Группы при первом входе'),
        ),
    ]
