# Generated by Django 6.0.7 on 2026-08-29 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_alter_alloweduser_options_alloweduser_initial_groups'),
        ('integrations', '0013_okdeskinstance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userokdesktoken',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tokens', to='integrations.okdeskinstance', verbose_name='Инстанс Okdesk'),
        ),
        migrations.AlterField(
            model_name='userokdesktoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okdesk_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='userokdesktoken',
            constraint=models.UniqueConstraint(fields=('user', 'instance'), name='uniq_okdesktoken_user_instance'),
        ),
    ]
