# Generated by Django 6.0.7 on 2026-08-18 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('access', '0009_notification'), ('access', '0010_alter_notification_kind')]

    dependencies = [
        ('access', '0008_alter_alloweduser_options_alloweduser_initial_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service_request_reply', 'Ответ по заявке подрядчику'), ('mailbox_quota', 'Ящик сервис-деска заполняется')], db_index=True, max_length=32, verbose_name='Вид')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Пояснение')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('target_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Объект')),
                ('event_key', models.CharField(blank=True, max_length=100, verbose_name='Событие')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='access_noti_user_id_07b35d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_key', ''), _negated=True), fields=('user', 'event_key'), name='uniq_notification_event')],
            },
        ),
    ]
